POST {{baseUrl}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Clean my room",
  "description": "Lots of cleaning has to be done"
}

> {% client.global.set('taskId', response.body.id) %}

###
GET {{baseUrl}}/tasks
Authorization: Bearer {{token}}

> {% client.global.set('taskId', response.body[0].id) %}

###
GET {{baseUrl}}/tasks?status=OPEN&search=room
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}

###
PATCH {{baseUrl}}/tasks/{{taskId}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

###
DELETE {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
