POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Clean my room",
  "description": "Lots of cleaning has to be done"
}

> {% client.global.set('taskId', response.body.id) %}

###
GET {{baseUrl}}/tasks

###
GET {{baseUrl}}/tasks/{{taskId}}

###
DELETE {{baseUrl}}/{{taskId}}
