POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Clean my room",
  "description": "Lots of cleaning has to be done"
}

> {% client.global.set('taskId', response.body.id) %}

###
GET {{baseUrl}}/tasks

> {% client.global.set('taskId', response.body[0].id) %}

###
GET {{baseUrl}}/tasks?status=OPEN&search=room

###
GET {{baseUrl}}/tasks/{{taskId}}

###
PATCH {{baseUrl}}/tasks/{{taskId}}/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

###
DELETE {{baseUrl}}/tasks/{{taskId}}
